### ISSUE TITLE
torch cuda synchronize on GPUs?

### ISSUE THREAD

**Issue by jizongFox** [LukasHedegaard/pytorch-benchmark#11]
Hello, 

Very happy to see your repo. 

I have tested the code and found that for the GPU tests, there may lack of torch synchronize when computing the device time. I am not sure how this may impact the results but I think it would make difference. 

What do you think?

Best,

**Comment by LukasHedegaard** [comment]
Thank you for the suggestion, but I believe that the transfer of data to cpu after each call makes `torch.cuda.synchronize` redundant
