### ISSUE TITLE
can this benchmark be run on older pytorch releases?

### ISSUE THREAD

**Issue by joepareti54** [LukasHedegaard/pytorch-benchmark#14]
$ conda create --name myenv_Pytorch1.8.0
$ conda activate myenv_Pytorch1.8.0
$ conda install pytorch==1.8.0 torchvision==0.9.0 torchaudio==0.8.0 cudatoolkit=10.2 -c pytorch

$python script.py #python code provided in the README file

ImportError: cannot import name 'efficientnet_b0' from 'torchvision.models'

**Comment by LukasHedegaard** [comment]
Hi @joepareti54, I believe the above error relates to the Torchvision release, not the PyTorch release. It should work with PyTorch 1.x and 2.x. You can check your torchvision release (0.9.0) and try with a supported model.
